// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SwissCovid.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum VenueType: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case other // = 0
  case meetingRoom // = 1
  case cafeteria // = 2
  case privateEvent // = 3
  case canteen // = 4
  case library // = 5
  case lectureRoom // = 6
  case shop // = 7
  case gym // = 8
  case kitchenArea // = 9
  case officeSpace // = 10
  case UNRECOGNIZED(Int)

  init() {
    self = .other
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .other
    case 1: self = .meetingRoom
    case 2: self = .cafeteria
    case 3: self = .privateEvent
    case 4: self = .canteen
    case 5: self = .library
    case 6: self = .lectureRoom
    case 7: self = .shop
    case 8: self = .gym
    case 9: self = .kitchenArea
    case 10: self = .officeSpace
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .other: return 0
    case .meetingRoom: return 1
    case .cafeteria: return 2
    case .privateEvent: return 3
    case .canteen: return 4
    case .library: return 5
    case .lectureRoom: return 6
    case .shop: return 7
    case .gym: return 8
    case .kitchenArea: return 9
    case .officeSpace: return 10
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension VenueType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [VenueType] = [
    .other,
    .meetingRoom,
    .cafeteria,
    .privateEvent,
    .canteen,
    .library,
    .lectureRoom,
    .shop,
    .gym,
    .kitchenArea,
    .officeSpace,
  ]
}

#endif  // swift(>=4.2)

enum EventCriticality: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case low // = 0
  case high // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .low
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .low
    case 1: self = .high
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .low: return 0
    case .high: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension EventCriticality: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [EventCriticality] = [
    .low,
    .high,
  ]
}

#endif  // swift(>=4.2)

struct SwissCovidLocationData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var version: UInt32 = 0

  var type: VenueType = .other

  var room: String = String()

  var checkoutWarningDelayMs: Int64 = 0

  var automaticCheckoutDelaylMs: Int64 = 0

  var reminderDelayOptionsMs: [Int64] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SwissCovidAssociatedData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var version: Int32 = 0

  var room: String = String()

  var criticality: EventCriticality = .low

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension VenueType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OTHER"),
    1: .same(proto: "MEETING_ROOM"),
    2: .same(proto: "CAFETERIA"),
    3: .same(proto: "PRIVATE_EVENT"),
    4: .same(proto: "CANTEEN"),
    5: .same(proto: "LIBRARY"),
    6: .same(proto: "LECTURE_ROOM"),
    7: .same(proto: "SHOP"),
    8: .same(proto: "GYM"),
    9: .same(proto: "KITCHEN_AREA"),
    10: .same(proto: "OFFICE_SPACE"),
  ]
}

extension EventCriticality: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LOW"),
    1: .same(proto: "HIGH"),
  ]
}

extension SwissCovidLocationData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SwissCovidLocationData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "version"),
    2: .same(proto: "type"),
    3: .same(proto: "room"),
    4: .same(proto: "checkoutWarningDelayMs"),
    5: .same(proto: "automaticCheckoutDelaylMs"),
    6: .same(proto: "reminderDelayOptionsMs"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.version) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.room) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.checkoutWarningDelayMs) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.automaticCheckoutDelaylMs) }()
      case 6: try { try decoder.decodeRepeatedInt64Field(value: &self.reminderDelayOptionsMs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.version != 0 {
      try visitor.visitSingularUInt32Field(value: self.version, fieldNumber: 1)
    }
    if self.type != .other {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    if !self.room.isEmpty {
      try visitor.visitSingularStringField(value: self.room, fieldNumber: 3)
    }
    if self.checkoutWarningDelayMs != 0 {
      try visitor.visitSingularInt64Field(value: self.checkoutWarningDelayMs, fieldNumber: 4)
    }
    if self.automaticCheckoutDelaylMs != 0 {
      try visitor.visitSingularInt64Field(value: self.automaticCheckoutDelaylMs, fieldNumber: 5)
    }
    if !self.reminderDelayOptionsMs.isEmpty {
      try visitor.visitPackedInt64Field(value: self.reminderDelayOptionsMs, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SwissCovidLocationData, rhs: SwissCovidLocationData) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs.type != rhs.type {return false}
    if lhs.room != rhs.room {return false}
    if lhs.checkoutWarningDelayMs != rhs.checkoutWarningDelayMs {return false}
    if lhs.automaticCheckoutDelaylMs != rhs.automaticCheckoutDelaylMs {return false}
    if lhs.reminderDelayOptionsMs != rhs.reminderDelayOptionsMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SwissCovidAssociatedData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SwissCovidAssociatedData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "version"),
    2: .same(proto: "room"),
    3: .same(proto: "criticality"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.version) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.room) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.criticality) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.version != 0 {
      try visitor.visitSingularInt32Field(value: self.version, fieldNumber: 1)
    }
    if !self.room.isEmpty {
      try visitor.visitSingularStringField(value: self.room, fieldNumber: 2)
    }
    if self.criticality != .low {
      try visitor.visitSingularEnumField(value: self.criticality, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SwissCovidAssociatedData, rhs: SwissCovidAssociatedData) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs.room != rhs.room {return false}
    if lhs.criticality != rhs.criticality {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
