opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build and Sign app"
  lane :build_and_sign do

  setup_ci

  match(
    type: "appstore",
    readonly: is_ci,
    app_identifier: [ENV["APP_IDENTIFIER"], ENV["APP_IDENTIFIER"] + ".Clip" ].join(","),
  )

  update_code_signing_settings(
    use_automatic_signing: false,
    path: ENV["XCODE_PROJ"],
    code_sign_identity: "iPhone Distribution"
  )

  build_number = getCustomBundleVersion()
  add_badge(shield: ENV["BADGE_TITLE"]+ "-" + ENV['GITHUB_RUN_NUMBER'] + "-167cff", no_badge: true) unless ENV["SKIP_ADD_BADGE"]

  build_app(
    scheme: ENV["APP_SCHEME"],
    output_directory: "build/",
    output_name: "SwissCovid.ipa",
    archive_path: "build/SwissCovid.xcarchive",
    buildlog_path: "build/build.log",
    xcargs: "BUILD_NUMBER=#{build_number} PRIMARY_BUNDLE_IDENTIFIER=#{ENV["APP_IDENTIFIER"]} PROVISIONING_PROFILE_SPECIFIER='$(sigh_$(PRODUCT_BUNDLE_IDENTIFIER)_appstore_profile-name)' "
  )
  end

  def getCustomBundleVersion()
    datestring_now = DateTime.now.strftime('%y%m%d.%H%M')
    bundle_version = "#{datestring_now}.#{ENV['GITHUB_RUN_NUMBER']}#{ENV['BUILD_NUMBER_POSTFIX']}"
    return bundle_version
  end

   lane :test do
    multi_scan(
      scheme: "Debug",
      try_count: 3,
      parallel_testrun_count: 1,
      device: "iPhone 11 Pro"
    )
  end
end


